### ISSUE TITLE
YashKumar-CoreTeamLead-08042004

### ISSUE THREAD

**Issue by Yashkumxr** [DeCodeCafe/Onboarding-and-ToDo-List-#1]
# Welcome to the DeCodeCafe Community 🎉 
 
Hey 👋 ,
We're really excited to have you as part of the DeCodeCafe Community. Here is a list of ToDo items we need you to follow to complete your onboarding.

## Your ToDo List

- Onboarding
  - Please use this file as a template for onboarding and create an issue at [DeCodeCafe/Onboarding-and-ToDo-List-](https://github.com/DeCodeCafe/Onboarding-and-ToDo-List-/issues) and complete all the tasks here.
   Issue Format: NAME-ROLE-DDMMYYYY

- Terms of Service
  - [x] Please tick the checkbox to signify that you have read and agree to the DeCodeCafe Community terms and conditions: https://github.com/DeCodeCafe/Code-of-Conduct

- Discord
  - [x] Join the [Discord Server](https://discord.gg/4ScQzUQc35)
  - [x] Accept the server rules
  - [x] Change your alias on the server to be your Name
  - [x] Introduce yourself in the `🌱introductions` channel on Discord
  

- Community Profile

  - [x] Please create a file at [DeCodeCafe/Core-Team-Members](https://github.com/DeCodeCafe/Core-Team-Members) with your name (Eg: Rahul Khinchi.md)
  - [x] Please write about yourself. How about sharing your image, social links and some nice lines about you? Also, it's a .md file ( markdown file). Know more about it's [good practice](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

**Comment by Rahulkhinchi03** [comment]
✔️ Congratulations, I’ve approved your issue. Now you're officially a **Community Advocate** at DeCodeCafe Community!

Hey @Yashkumxr 👋 congratulations, this issue being closed means you have completed the DeCodeCafe Onboarding! 🚩

All set! ✅
