### ISSUE TITLE
ShubhaamTiwary_Community_Advocates_230082002

### ISSUE THREAD

**Issue by ShubhaamTiwary** [DeCodeCafe/Onboarding-and-ToDo-List-#19]
## I am Shubhaam Tiwary!🚀

🎓 I am a 3rd Year UG student , completing my Btech in CSIT from Symbiosis Indore . I love problem Solving -- DSA + CP 
## Your ToDo List

- Onboarding
  - Please use this file as a template for onboarding and create an issue at [DeCodeCafe/Onboarding-and-ToDo-List-](https://github.com/DeCodeCafe/Onboarding-and-ToDo-List-/issues) and complete all the tasks here.
   Issue Format: NAME-ROLE-DDMMYYYY

- Terms of Service
  - [x] Please tick the checkbox to signify that you have read and agree to the DeCodeCafe Community terms and conditions: https://github.com/DeCodeCafe/Code-of-Conduct

- Discord
  - [x] Join the [Discord Server](https://discord.gg/4ScQzUQc35)
  - [x] Accept the server rules
  - [x] Change your alias on the server to be your Name
  - [x] Introduce yourself in the `🌱introductions` channel on Discord
  

- Community Profile

  - [x] Please create a file at [DeCodeCafe/Core-Team-Members](https://github.com/DeCodeCafe/Core-Team-Members) with your name (Eg: Rahul Khinchi.md)
  - [x] Please write about yourself. How about sharing your image, social links and some nice lines about you? Also, it's a .md file ( markdown file). Know more about it's [good practice](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

### Note
To tick the box: You need to write X in the box. 

<h3 align="left">Connect with me:</h3>
<p align="left">
<p align="left"> 
 <a href="https://www.linkedin.com/in/shubhaam-tiwary-10302a202//" target="_blank" rel="noreferrer"><img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" width="32" height="32" /></a> 
<a href="https://leetcode.com/shubhaamtiwary_01/" target="blank"><img  src="https://user-images.githubusercontent.com/36547915/97088991-45da5d00-1652-11eb-900f-80d106540f4f.png" alt="Ankit Raj" height="32" width="32" /></a> 
 </p>

**Comment by Rahulkhinchi03** [comment]
@ShubhaamTiwary please add the X in the box correctly.

Invalid:
[ x]
[x ]

Valid:
[x]

**Comment by ShubhaamTiwary** [comment]
> @ShubhaamTiwary please add the X in the box correctly.
> 
> Invalid: [ x] [x ]
> 
> Valid: [x]

Done

**Comment by Rahulkhinchi03** [comment]
✔️ Congratulations, I’ve approved your issue. Now you're officially a Community Advocate at DeCodeCafe Community!

Hey @ShubhaamTiwary  👋 congratulations, this issue being closed means you have completed the DeCodeCafe Onboarding! 🚩

All set! ✅
