### ISSUE TITLE
KriteshOjha-CommunityManager-25022003

### ISSUE THREAD

**Issue by k-rite** [DeCodeCafe/Onboarding-and-ToDo-List-#2]
# Welcome to the DeCodeCafe Community 🎉 
 
Hey 👋 ,
We're really excited to have you as part of the DeCodeCafe Community. Here is a list of ToDo items we need you to follow to complete your onboarding.

## Your ToDo List

- Onboarding
  - Please use this file as a template for onboarding and create an issue at [DeCodeCafe/Onboarding-and-ToDo-List-](https://github.com/DeCodeCafe/Onboarding-and-ToDo-List-/issues) and complete all the tasks here.
   Issue Format: NAME-ROLE-DDMMYYYY

- Terms of Service
  - [X] Please tick the checkbox to signify that you have read and agree to the DeCodeCafe Community terms and conditions: https://github.com/DeCodeCafe/Code-of-Conduct

- Discord
  - [X] Join the [Discord Server](https://discord.gg/4ScQzUQc35)
  - [X] Accept the server rules
  - [X] Change your alias on the server to be your Name
  - [X] Introduce yourself in the `🌱introductions` channel on Discord
  

- Community Profile

  - [X] Please create a file at [DeCodeCafe/Core-Team-Members](https://github.com/DeCodeCafe/Core-Team-Members) with your name (Eg: Rahul Khinchi.md)
  - [X] Please write about yourself. How about sharing your image, social links and some nice lines about you? Also, it's a .md file ( markdown file). Know more about it's [good practice](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

### Note
To tick the box: You need to write X in the box.

**Comment by Rahulkhinchi03** [comment]
@k-rite please complete the community profile step in order to complete the onboarding!

**Comment by k-rite** [comment]
check @Rahulkhinchi03

**Comment by Rahulkhinchi03** [comment]
@k-rite I cannot see your PR at https://github.com/DeCodeCafe/Core-Team-Members/pulls

Please create a file at [DeCodeCafe/Core-Team-Members](https://github.com/DeCodeCafe/Core-Team-Members) with your name (Eg: Rahul Khinchi.md)

**Comment by k-rite** [comment]
check

**Comment by Rahulkhinchi03** [comment]
@k-rite https://github.com/DeCodeCafe/Core-Team-Members/pull/10#issuecomment-1381958673
