### ISSUE TITLE
Prajakta Kadam-Developer Advocate-08012000

### ISSUE THREAD

**Issue by Prajaktak8** [DeCodeCafe/Onboarding-and-ToDo-List-#20]
# Hello Everyone!:wave:

I am **Prajakta Kadam** , final year student at **Graphic Era Hill University, Dehradun** pursuing **B.Tech Computer Science**.
I have been selected as a **Developer Advocate** for **DecodeCafe Community**. I'm a Keen learner who loves technology.

<h3 align="left">Connect with me:</h3>
<p align="left"> 
 <a href="https://www.linkedin.com/in/Prajaktak8" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/socials/linkedin.svg" width="30" height="30" /></a> 
 <a href="https://twitter.com/PrajaktaK_8" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/socials/twitter.svg" width="30" height="30" /></a>
 </p>

Your ToDo List

Discord

[x ] Join the [Discord Server](https://discord.gg/4ScQzUQc35)
[ x] Accept the server rules
[x ] Change your alias on the server to be your Name
[ x] Introduce yourself in the 🌱introductions channel on Discord
Community Profile

[x ] Please create a file at [DeCodeCafe/Core-Team-Members](https://github.com/DeCodeCafe/Core-Team-Members) with your name (Eg: Rahul Khinchi.md)
[x ] Please write about yourself. How about sharing your image, social links and some nice lines about you? Also, it's a .md file ( markdown file). Know more about it's [good practice](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

**Comment by Rahulkhinchi03** [comment]
@Prajaktak8 please add the `X` in the box correctly.

Invalid:
[ x]
[x ]

Valid:
[x]
